version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
    open-pull-requests-limit: 10
    reviewers:
      - Mostafa-SAID7
    allow:
      - dependency-type: all
