# GitHub Sponsors
github: [Mostafa-SAID7]

# Patreon
patreon: WE3DSSolutions

# Buy Me a Coffee
buy_me_a_coffee: we3dssolutc

# Ko-fi
ko_fi: we3dssolutions

# Thanks.dev
thanks_dev: gh/we3ds-company

# Custom links
custom:
  - https://we3ds.com
